name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write
            repository-projects: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.17"

            - name: Install Dependencies
              run: npm install

            - name: Semantic Release
              run: npx semantic-release
