name: Release

on:
    push:
        branches:
            - main
    pull_request:
        branches: -develop

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write
            repository-projects: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.17"

            - name: Install Dependencies
              run: npm install

            - name: Semantic Release
              run: npx semantic-release
